---
- name: Download Apache Kafka Locally
  get_url:
    url: https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
  delegate_to: 127.0.0.1
